# Generated by Django 4.1.2 on 2022-10-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="phone",),
    ]
