# Generated by Django 4.0.5 on 2022-07-03 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='path',
            field=models.CharField(default=datetime.datetime(2022, 7, 3, 15, 32, 19, 538445, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
