# Generated by Django 4.0.5 on 2022-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_remove_qrcode_image_qrcode_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='path',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcodes/images/'),
        ),
    ]
