# Generated by Django 4.0.5 on 2022-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_remove_qrcode_file_qrcode_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='path',
            new_name='file_name',
        ),
    ]
