# Generated by Django 4.0.5 on 2022-07-03 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_rename_path_qrcode_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='file_name',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='file',
            field=models.FileField(default=datetime.datetime(2022, 7, 3, 16, 46, 32, 139870, tzinfo=utc), upload_to='media/qrcodes/'),
            preserve_default=False,
        ),
    ]
